### ISSUE TITLE
Please provide examples for which the auto-completion is working with semantics

### ISSUE THREAD

**Issue by maestroe** [OpenBEL/openbel-api#139]
The built-in auto-completion in the BELMgr was tested with following examples:
- `rxn` => delivers reaction method and several other EGID entries => Works
- `rxn(r` => delivers all methods and the RGD namespace => not working
- `a` => delivers abundance, complexAbundance and some other methods. By choosing complexAbundance, the BELMgr outputs complex() and the cursor jumps to the end position. Apparently, the caret position is not being considered. => not working

Using the BEL 2.0 endpoint. Also the API is returning the results very slow.

**Comment by wshayes** [comment]
Examples:  https://openbel.api-docs.io/1.1.0/api/eaQDzzCpGuHQ6Di2E

For completing on namespace values, it will not respond with less than 3 characters. 

The ordering of the completions is up to the client.

Tony - can you provide more detail on when it will provide semantically valid results vs not or more examples with more of a description of the results?

**Comment by wshayes** [comment]
Regarding the BELMgr caret position, this is a known issue (#belmgr/85) and not planned to be fixed in the near term.  The API is providing the correct caret position.

**Comment by wshayes** [comment]
In the BELMgr - we don't kill requests to the autocomplete service due to an issue with how we handle promises.  This causes extra latency in the BELMgr autocompletes.  It's also a complex autocomplete and has been optimized significantly already, but we agree that it is still not fast enough.  More optimizations, however, are out of scope for the BELIEF milestone.

Details on how promises are handled:
http://stackoverflow.com/questions/29478751/how-to-cancel-an-emcascript6-vanilla-javascript-promise-chain
